# Generated by Django 5.0.4 on 2024-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer_date_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
