# Generated by Django 5.0.4 on 2024-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_survey_city_survey_last_name_survey_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='city',
            field=models.CharField(default=2, max_length=20, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='last_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
    ]
