# Generated by Django 5.0.4 on 2024-05-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_options_rename_text_question_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='bio',
            new_name='text',
        ),
    ]
